on:
  push:
    branches:
      - "feature/deploy-sb"

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          path: storybook-static
